### PR TITLE
Specify anchor plate ID when resolving topologies

### PR DESCRIPTION
**Pull request by cpalfonso**
The `resolve_topologies` and `resolve_topologies_into_features` functions now have an optional `anchor_plate_id` parameter (default 0).
If the installed pyGPlates version is earlier than 0.26 and a non-zero plate ID is specified, a RuntimeError is raised, consistent with the current behaviour when `resolve_topologies.py` is run as a script.

These changes are needed to implement GPlates/gplately#47 .

### CODE REVIEW

**Comment by jcannon-gplates** [comment]
I think the min version needs to be pyGPlates 0.29 for these parts...

```
    if USING_PYGPLATES_VERSION_GREATER_EQUAL_26:
        rotation_model = pygplates.RotationModel(
            rotation_features_or_model,
            default_anchor_plate_id=anchor_plate_id,
        )
```

...in case `rotation_features_or_model` is a `pygplates.RotationModel` (the second `__init__` [here](https://www.gplates.org/docs/pygplates/generated/pygplates.rotationmodel#pygplates.RotationModel.__init__) was introduced in 0.29).

However version 0.26 is ok in the following because it's only files...

```
rotation_model = pygplates.RotationModel(args.rotation_filenames, default_anchor_plate_id=args.anchor_plate_id)
```

**Comment by brmather** [comment]
Is this OK to be committed to the master branch?

**Comment by cpalfonso** [comment]
Sorry about that, I changed this a while back but must have forgotten to actually commit and push it. 
Looking at it a bit more closely, is the `USING_PYGPLATES_VERSION_GREATER_EQUAL_26` flag actually necessary? If we get rid of all of the `default_anchor_plate_id` arguments to `RotationModel` and just specify the `anchor_plate_id` argument every time we call `pygplates.resolve_topologies`, can we get around the fact that `default_anchor_plate_id` wasn't introduced until revision 26?

**Comment by jcannon-gplates** [comment]
You could do that, but you'd also need to modify [separate_ridge_transform_segments.get_stage_rotation_for_reconstructed_geometry](https://github.com/EarthByte/PlateTectonicTools/blob/760e46be2e3aebfec6b6ea09f738f5696f55167d/ptt/resolve_topologies.py#L218) to pass `anchor_plate_id`. Probably easier to avoid that and just change `USING_PYGPLATES_VERSION_GREATER_EQUAL_26` to `USING_PYGPLATES_VERSION_GREATER_EQUAL_29`. Now that pyGPlates 0.36 is public maybe it's not too bad to require something (0.29) that's above the previous public release 0.28?  And if they're using less than 0.29 then the exception is only raised if they're using a _non-zero_ `anchor_plate_id` (so upgrading to the latest public release could be the price they pay for using a non-zero `anchor_plate_id`).

Also it might be a good idea to make the `anchor_plate_id` argument to `resolve_topologies.resolved_topologies` default to `None` (instead of defaulting to `0` as you currently do). In this way if the user passes in a `pygplates.RotationModel` then they may have already specified a default anchor plate ID inside that, and don't want to have to specify it again to `resolve_topologies.resolved_topologies` (or don't want to have it default to `0` and override what they're using inside their `pygplates.RotationModel`). If `anchor_plate_id` instead defaults `None` then it only gets overridden if the user actually specifies it. And if the user passes rotation features (instead of a `pygplates.RotationModel`) into `resolve_topologies.resolved_topologies` then a default `anchor_plate_id` of `None` means anchor plate `0`.

In fact I think defaulting to `None` is needed. So I'd suggest the following (which is a combination of the previous two paragraphs)...

```
    # Turn rotation data into a RotationModel (if not already).
    if anchor_plate_id is not None:
        if USING_PYGPLATES_VERSION_GREATER_EQUAL_29:
            rotation_model = pygplates.RotationModel(
                rotation_features_or_model,
                default_anchor_plate_id=anchor_plate_id,
            )
        else:
            raise RuntimeError('Using pygplates version {0} but version 29 or greater is required for non-zero anchor plate IDs'.format(
            pygplates.Version.get_imported_version()))
    else:
        rotation_model = pygplates.RotationModel(rotation_features_or_model)
```

And for the command-line argument (`if args.anchor_plate_id != 0:`) you can leave it defaulting to zero (as it currently is) since we know we're using rotation features there (not a `pygplates.RotationModel`).

**Comment by brmather** [comment]
@cpalfonso is there any progress to report on this PR?

**Comment by cpalfonso** [comment]
@brmather, sorry about the delay - I guess this sort of fell off the radar. I've added a new function to `resolve_topologies.py` (`_parse_rotation_args`), which should be able to handle all of the different cases here: input in `RotationModel` form or not, anchor plate ID specified or not, and pygplates version greater than 0.26/0.29 or not. 

@jcannon-gplates can you identify any cases that I might have missed here?

**Comment by jcannon-gplates** [comment]
Thanks, that's great!  You even support non-zero anchor plate IDs back to pyGPlates version 0.26 where possible (ie, before 0.29).

**Pull request merged**
